
export const SET_USER = 'SET_USER';
export const SET_REPOSITORIES = 'SET_REPOSITORIES';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_SELECTED_REPO = 'SET_SELECTED_REPO';
export const SET_SELECTED_FOLLOWER = 'SET_SELECTED_FOLLOWER';
